name = "tambouille"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tambouille-db"
database_id = "PLACEHOLDER_RUN_WRANGLER_D1_CREATE"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "tambouille-images"
